web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code/src
  ports:
    - "8000:8000"
  links:
    - memcached
  volumes:
    - .:/code
  environment:
    MEMCACHED_HOST: memcached
    MEMCACHED_PORT: 11211

memcached:
   hostname: memcached
   image: memcached
   environment:
     MEMCACHED_MEMORY_LIMIT: 128
